### ISSUE TITLE
Wrong InvalidAddressError message

### ISSUE THREAD

**Issue by tapalilov** [ruby/ipaddr#60]
After changes from https://github.com/ruby/ipaddr/pull/16 and removing of 
```
  rescue InvalidAddressError => e
    raise e.class, "#{e.message}: #{addr}"
```
exception no longer returns proper exception message with invalid ip address.

ruby 3.0
```
> IPAddr.new('192.168.0.1000')
ipaddr.rb:598:in `rescue in initialize': invalid address: 192.168.0.1000 (IPAddr::InvalidAddressError)
```
ruby 3.1
```
> IPAddr.new('192.168.0.1000')
ipaddr.rb:656:in `block in in_addr': invalid address:  (IPAddr::InvalidAddressError)
```

**Comment by tatethurston** [comment]
Yeah this regression impacts 1.2.3 and later.
