### ISSUE TITLE
Getting IPAddr::InvalidAddressError on valid domain look-ups

### ISSUE THREAD

**Issue by melroy89** [ruby/ipaddr#81]
Hi,

I create an issue here, since I believe it's a bug in **Ruby** and _not_ in Mastodon (v4.3.1).

I'm getting `IPAddr::InvalidAddressError` errors on valid valid requests / domains. I have IPv6 disabled.

And yes, the DNS server returns a valid response on the server as well as within the docker container. To confirm it's not an issue with the network, I executed a simple `curl` request. Eor example (on the VM as well as _in_ the docker containers):

```sh
curl https://mstdn.social/.well-known/webfinger?resource=acct:BrodieOnLinux@mstdn.social
```

All works fine! IP address gets resolved and I see JSON content. No problems.

However, within the same Docker container **Ruby** is used for running Mastodon, and I get:

```sh
E, [2024-11-06T23:27:12.958411 #17] ERROR -- : [1769c3f3-7bed-4450-b12d-c0588904c87e]   
[1769c3f3-7bed-4450-b12d-c0588904c87e] IPAddr::InvalidAddressError (invalid address:  on https://mstdn.social/.well-known/webfinger?resource=acct:BrodieOnLinux@mstdn.social):
[1769c3f3-7bed-4450-b12d-c0588904c87e]   

E, [2024-11-06T23:27:51.629513 #17] ERROR -- : [3135ff53-4d01-479f-abaa-1f92ab402eea]   
[3135ff53-4d01-479f-abaa-1f92ab402eea] IPAddr::InvalidAddressError (invalid address:  on https://mastodon.online/.well-known/webfinger?resource=acct:bronxasaur@mastodon.online):
[3135ff53-4d01-479f-abaa-1f92ab402eea]   
```

Sidekiq logs in Mastodon:

```sh
2024-11-06T23:56:01.249Z pid=7 tid=4g63 WARN: IPAddr::InvalidAddressError: invalid address:  on https://gehirneimer.de/f/inbox
2024-11-06T23:56:01.249Z pid=7 tid=4g63 WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:07.067Z pid=7 tid=4gaj WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://toot.wales/inbox"],"jid":"cc72ae9d463100f245231110","created_at":1730935917.821262,"enqueued_at":1730937367.0606325,"error_message":"https://toot.wales/inbox","error_class":"Stoplight::Error::RedLight","failed_at":1730935917.972108,"retry_count":5,"retried_at":1730936551.846972}}
2024-11-06T23:56:07.068Z pid=7 tid=4gaj WARN: Stoplight::Error::RedLight: https://toot.wales/inbox
2024-11-06T23:56:07.068Z pid=7 tid=4gaj WARN: /usr/local/bundle/gems/stoplight-4.1.0/lib/stoplight/light/runnable.rb:70:in `run_red'
/usr/local/bundle/gems/stoplight-4.1.0/lib/stoplight/light/runnable.rb:33:in `run'
/usr/local/lib/ruby/3.3.0/forwardable.rb:240:in `run'
2024-11-06T23:56:07.068Z pid=7 tid=4g93 WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://gehirneimer.de/f/inbox"],"jid":"2f999bf9a8a7af7cb9c03de7","created_at":1730935917.821262,"enqueued_at":1730937367.0616448,"error_message":"https://gehirneimer.de/f/inbox","error_class":"Stoplight::Error::RedLight","failed_at":1730935917.8539855,"retry_count":5,"retried_at":1730936508.5231423}}
2024-11-06T23:56:07.070Z pid=7 tid=4g93 WARN: Stoplight::Error::RedLight: https://gehirneimer.de/f/inbox
2024-11-06T23:56:07.070Z pid=7 tid=4g93 WARN: /usr/local/bundle/gems/stoplight-4.1.0/lib/stoplight/light/runnable.rb:70:in `run_red'
/usr/local/bundle/gems/stoplight-4.1.0/lib/stoplight/light/runnable.rb:33:in `run'
/usr/local/lib/ruby/3.3.0/forwardable.rb:240:in `run'
2024-11-06T23:56:07.078Z pid=7 tid=4ga7 WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"sensitive\":\"as:sensitive\",\"toot\":\"http://joinmastodon.org/ns#\",\"votersCount\":\"toot:votersCount\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/activity\",\"type\":\"Create\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"published\":\"2024-11-06T23:31:45Z\",\"to\":[\"https://mastodon.melroy.org/users/melroy/followers\"],\"cc\":[],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Note\",\"summary\":null,\"inReplyTo\":null,\"published\":\"2024-11-06T23:31:45Z\",\"url\":\"https://mastodon.melroy.org/@melroy/113438615504018032\",\"attributedTo\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://mastodon.melroy.org/users/melroy/followers\"],\"cc\":[],\"sensitive\":false,\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"inReplyToAtomUri\":null,\"conversation\":\"tag:mastodon.melroy.org,2024-11-06:objectId=2094880:objectType=Conversation\",\"content\":\"<p>Can somebody see this?</p>\",\"contentMap\":{\"en\":\"<p>Can somebody see this?</p>\"},\"attachment\":[],\"tag\":[],\"replies\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/replies\",\"type\":\"Collection\",\"first\":{\"type\":\"CollectionPage\",\"next\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/replies?only_other_accounts=true&page=true\",\"partOf\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/replies\",\"items\":[]}},\"likes\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/likes\",\"type\":\"Collection\",\"totalItems\":0},\"shares\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/shares\",\"type\":\"Collection\",\"totalItems\":0}}}",109367497985816347,"https://mastodon.online/inbox",{"synchronize_followers":true}],"jid":"5fe686932b7d498c2bd6bb4b","created_at":1730935905.7580423,"enqueued_at":1730937367.0594404,"error_message":"invalid address:  on https://mastodon.online/inbox","error_class":"IPAddr::InvalidAddressError","failed_at":1730935906.3569305,"retry_count":5,"retried_at":1730936461.1019673}}
2024-11-06T23:56:07.078Z pid=7 tid=4ga7 WARN: IPAddr::InvalidAddressError: invalid address:  on https://mastodon.online/inbox
2024-11-06T23:56:07.078Z pid=7 tid=4ga7 WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:09.666Z pid=7 tid=4g9f WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://pol.social/inbox"],"jid":"3790dcfd5ce26b939e50d3d5","created_at":1730935917.821262,"enqueued_at":1730937369.6425984,"error_message":"https://pol.social/inbox","error_class":"Stoplight::Error::RedLight","failed_at":1730935917.953392,"retry_count":5,"retried_at":1730936562.526859}}
2024-11-06T23:56:09.666Z pid=7 tid=4g9f WARN: IPAddr::InvalidAddressError: invalid address:  on https://pol.social/inbox
2024-11-06T23:56:09.666Z pid=7 tid=4g9f WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:09.782Z pid=7 tid=4g8b WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"ingress","backtrace":true,"args":[109632981772261007,"{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://infosec.exchange/users/Em0nM4stodon/statuses/113438707739406718/activity\",\"type\":\"Announce\",\"actor\":\"https://infosec.exchange/users/Em0nM4stodon\",\"published\":\"2024-11-06T23:55:12Z\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://syzito.xyz/users/selzero\",\"https://infosec.exchange/users/Em0nM4stodon/followers\"],\"object\":\"https://syzito.xyz/users/selzero/statuses/113436846334826263\"}",null,"Account"],"class":"ActivityPub::ProcessingWorker","jid":"59aa4898ea23fe6ff9253948","created_at":1730937314.5089526,"enqueued_at":1730937369.6437025,"error_message":"invalid address:  on https://syzito.xyz/users/selzero/statuses/113436846334826263","error_class":"IPAddr::InvalidAddressError","failed_at":1730937314.6389003,"retry_count":1,"error_backtrace":"eJyLVtIvLS7Sz8lPTszRz8lM0i8qTarUN9Yz1jPQzyxITEkp0itKsjKzNLLK\nzFNIyMwziweJqSvFAgAgkRJ3\n","retried_at":1730937341.1515217}}
2024-11-06T23:56:09.782Z pid=7 tid=4g8b WARN: IPAddr::InvalidAddressError: invalid address:  on https://syzito.xyz/users/selzero/statuses/113436846334826263
2024-11-06T23:56:09.782Z pid=7 tid=4g8b WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:16.225Z pid=7 tid=4gh7 WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://mastodon.online/inbox"],"jid":"2742b8c06b855ba7d32cddf0","created_at":1730935917.821262,"enqueued_at":1730937376.2227123,"error_message":"https://mastodon.online/inbox","error_class":"Stoplight::Error::RedLight","failed_at":1730935917.8994334,"retry_count":5,"retried_at":1730936490.8749497}}
2024-11-06T23:56:16.225Z pid=7 tid=4gh7 WARN: Stoplight::Error::RedLight: https://mastodon.online/inbox
2024-11-06T23:56:16.225Z pid=7 tid=4gh7 WARN: /usr/local/bundle/gems/stoplight-4.1.0/lib/stoplight/light/runnable.rb:70:in `run_red'
/usr/local/bundle/gems/stoplight-4.1.0/lib/stoplight/light/runnable.rb:33:in `run'
/usr/local/lib/ruby/3.3.0/forwardable.rb:240:in `run'
2024-11-06T23:56:20.638Z pid=7 tid=4gj3 WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://social.vivaldi.net/inbox"],"jid":"fd1147f74bed96f27dbf0f96","created_at":1730935917.821262,"enqueued_at":1730937380.621521,"error_message":"https://social.vivaldi.net/inbox","error_class":"Stoplight::Error::RedLight","failed_at":1730935917.961836,"retry_count":5,"retried_at":1730936484.5508044}}
2024-11-06T23:56:20.638Z pid=7 tid=4gj3 WARN: IPAddr::InvalidAddressError: invalid address:  on https://social.vivaldi.net/inbox
2024-11-06T23:56:20.638Z pid=7 tid=4gj3 WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:20.665Z pid=7 tid=4gib WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"sensitive\":\"as:sensitive\",\"toot\":\"http://joinmastodon.org/ns#\",\"votersCount\":\"toot:votersCount\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/activity\",\"type\":\"Create\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"published\":\"2024-11-06T23:31:45Z\",\"to\":[\"https://mastodon.melroy.org/users/melroy/followers\"],\"cc\":[],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Note\",\"summary\":null,\"inReplyTo\":null,\"published\":\"2024-11-06T23:31:45Z\",\"url\":\"https://mastodon.melroy.org/@melroy/113438615504018032\",\"attributedTo\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://mastodon.melroy.org/users/melroy/followers\"],\"cc\":[],\"sensitive\":false,\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"inReplyToAtomUri\":null,\"conversation\":\"tag:mastodon.melroy.org,2024-11-06:objectId=2094880:objectType=Conversation\",\"content\":\"<p>Can somebody see this?</p>\",\"contentMap\":{\"en\":\"<p>Can somebody see this?</p>\"},\"attachment\":[],\"tag\":[],\"replies\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/replies\",\"type\":\"Collection\",\"first\":{\"type\":\"CollectionPage\",\"next\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/replies?only_other_accounts=true&page=true\",\"partOf\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/replies\",\"items\":[]}},\"likes\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/likes\",\"type\":\"Collection\",\"totalItems\":0},\"shares\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032/shares\",\"type\":\"Collection\",\"totalItems\":0}}}",109367497985816347,"https://chaos.social/inbox",{"synchronize_followers":true}],"jid":"5b9a8956a20ab2c957b5c380","created_at":1730935905.7580423,"enqueued_at":1730937380.62045,"error_message":"invalid address:  on https://chaos.social/inbox","error_class":"IPAddr::InvalidAddressError","failed_at":1730935905.8154202,"retry_count":5,"retried_at":1730936424.0587416}}
2024-11-06T23:56:20.665Z pid=7 tid=4gib WARN: IPAddr::InvalidAddressError: invalid address:  on https://chaos.social/inbox
2024-11-06T23:56:20.665Z pid=7 tid=4gib WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:25.762Z pid=7 tid=4gmr WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://mastodon.green/inbox"],"jid":"6fa077dd243e632f4808b8b0","created_at":1730935917.821262,"enqueued_at":1730937385.7479606,"error_message":"https://mastodon.green/inbox","error_class":"Stoplight::Error::RedLight","failed_at":1730935917.8881156,"retry_count":5,"retried_at":1730936581.3251836}}
2024-11-06T23:56:25.762Z pid=7 tid=4gmr WARN: IPAddr::InvalidAddressError: invalid address:  on https://mastodon.green/inbox
2024-11-06T23:56:25.762Z pid=7 tid=4gmr WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:25.764Z pid=7 tid=4gnj WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://mastodon.xyz/inbox"],"jid":"d82275ae495148e82b39eb85","created_at":1730935917.821262,"enqueued_at":1730937385.7489147,"error_message":"invalid address:  on https://mastodon.xyz/inbox","error_class":"IPAddr::InvalidAddressError","failed_at":1730935917.915869,"retry_count":5,"retried_at":1730936490.8833063}}
2024-11-06T23:56:25.764Z pid=7 tid=4gnj WARN: IPAddr::InvalidAddressError: invalid address:  on https://mastodon.xyz/inbox
2024-11-06T23:56:25.764Z pid=7 tid=4gnj WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
2024-11-06T23:56:29.198Z pid=7 tid=4gr7 WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\"}],\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032#delete\",\"type\":\"Delete\",\"actor\":\"https://mastodon.melroy.org/users/melroy\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\",\"type\":\"Tombstone\",\"atomUri\":\"https://mastodon.melroy.org/users/melroy/statuses/113438615504018032\"}}",109367497985816347,"https://masto.ai/inbox"],"jid":"c9f92eea520cd6cc4f22d6e1","created_at":1730935917.821262,"enqueued_at":1730937389.1850557,"error_message":"invalid address:  on https://masto.ai/inbox","error_class":"IPAddr::InvalidAddressError","failed_at":1730935917.8830554,"retry_count":5,"retried_at":1730936581.3350892}}
2024-11-06T23:56:29.198Z pid=7 tid=4gr7 WARN: IPAddr::InvalidAddressError: invalid address:  on https://masto.ai/inbox
2024-11-06T23:56:29.198Z pid=7 tid=4gr7 WARN: /usr/local/lib/ruby/3.3.0/ipaddr.rb:692:in `in6_addr'
```

Mastodon ticket: https://github.com/mastodon/mastodon/issues/32792

[Ruby version](https://github.com/mastodon/mastodon/blob/main/Gemfile#L4): 

```
ruby --version
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [x86_64-linux]
```

**Comment by taketo1113** [comment]
Referring to the following comment in the Mastodon issue, it appears that this problem is specific to Mastodon (not the `ipaddr` gem).
The following PR in Mastodon has been updated to make the error easier to identify:
https://github.com/mastodon/mastodon/issues/32792#issuecomment-2465251756
https://github.com/mastodon/mastodon/pull/32850


It seems that improving the error message when passing an invalid string as an argument to `IPAddr.new` would make troubleshooting easier. This improvement will be addressed in the PR for #70.

**Comment by melroy89** [comment]
Agreed, this error message was very very misleading by Mastodon. And it doesn't seems to be an issue with ipaddr.
